//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.KL_API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", ConfigurationName="KL_API.KasperskySubscriptionServicePortType")]
    public interface KasperskySubscriptionServicePortType {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação SubscriptionRequest não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.kaspersky.com/services/subscription/subscriptionRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BLL.KL_API.SubscriptionRequestResponse SubscriptionRequest(BLL.KL_API.SubscriptionRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.kaspersky.com/services/subscription/subscriptionRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.KL_API.SubscriptionRequestResponse> SubscriptionRequestAsync(BLL.KL_API.SubscriptionRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class AccessInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseErrorCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseItemErrorType[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivateError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetDownloadLinksError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetInfoError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HardCancelError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PauseError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RenewError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ResumeError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SoftCancelError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ResponseItemErrorType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class ResponseItemErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        ActivateError,
        
        /// <remarks/>
        GetDownloadLinksError,
        
        /// <remarks/>
        GetInfoError,
        
        /// <remarks/>
        HardCancelError,
        
        /// <remarks/>
        PauseError,
        
        /// <remarks/>
        RenewError,
        
        /// <remarks/>
        ResumeError,
        
        /// <remarks/>
        SoftCancelError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activate", typeof(SubscriptionResponseItemCollectionActivate), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetDownloadLinks", typeof(SubscriptionResponseItemCollectionGetDownloadLinks), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetInfo", typeof(SubscriptionResponseItemCollectionGetInfo), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HardCancel", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Pause", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Renew", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Resume", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SoftCancel", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionActivate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string activationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("ActivationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionGetDownloadLinks : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetDownloadLinksInfo[] downloadLinksField;
        
        private PlatformEnum platformField;
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DownloadLink", IsNullable=false)]
        public GetDownloadLinksInfo[] DownloadLinks {
            get {
                return this.downloadLinksField;
            }
            set {
                this.downloadLinksField = value;
                this.RaisePropertyChanged("DownloadLinks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PlatformEnum Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("Platform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class GetDownloadLinksInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string urlField;
        
        private string languageField;
        
        private string alphabetField;
        
        private string regionField;
        
        private string rebrandingCodeField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
                this.RaisePropertyChanged("Alphabet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RebrandingCode {
            get {
                return this.rebrandingCodeField;
            }
            set {
                this.rebrandingCodeField = value;
                this.RaisePropertyChanged("RebrandingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("ApplicationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum PlatformEnum {
        
        /// <remarks/>
        Windows,
        
        /// <remarks/>
        macOS,
        
        /// <remarks/>
        Android,
        
        /// <remarks/>
        iOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionGetInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SubscriptionInfo subscriptionField;
        
        private SubscriptionUsageInfo subscriptionUsageField;
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SubscriptionInfo Subscription {
            get {
                return this.subscriptionField;
            }
            set {
                this.subscriptionField = value;
                this.RaisePropertyChanged("Subscription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubscriptionUsageInfo SubscriptionUsage {
            get {
                return this.subscriptionUsageField;
            }
            set {
                this.subscriptionUsageField = value;
                this.RaisePropertyChanged("SubscriptionUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SubscriptionStatusEnum statusField;
        
        private System.DateTime statusChangeTimeField;
        
        private bool statusChangeTimeFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private string endTimeField;
        
        private string licenseCountField;
        
        private string productIdField;
        
        private string activationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubscriptionStatusEnum Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StatusChangeTime {
            get {
                return this.statusChangeTimeField;
            }
            set {
                this.statusChangeTimeField = value;
                this.RaisePropertyChanged("StatusChangeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusChangeTimeSpecified {
            get {
                return this.statusChangeTimeFieldSpecified;
            }
            set {
                this.statusChangeTimeFieldSpecified = value;
                this.RaisePropertyChanged("StatusChangeTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
                this.RaisePropertyChanged("StartTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string LicenseCount {
            get {
                return this.licenseCountField;
            }
            set {
                this.licenseCountField = value;
                this.RaisePropertyChanged("LicenseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("ActivationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum SubscriptionStatusEnum {
        
        /// <remarks/>
        NotStarted,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        SoftCancelled,
        
        /// <remarks/>
        HardCancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionUsageInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime firstActivationTimeField;
        
        private bool firstActivationTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FirstActivationTime {
            get {
                return this.firstActivationTimeField;
            }
            set {
                this.firstActivationTimeField = value;
                this.RaisePropertyChanged("FirstActivationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstActivationTimeSpecified {
            get {
                return this.firstActivationTimeFieldSpecified;
            }
            set {
                this.firstActivationTimeFieldSpecified = value;
                this.RaisePropertyChanged("FirstActivationTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class BaseResponseItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Activate,
        
        /// <remarks/>
        GetDownloadLinks,
        
        /// <remarks/>
        GetInfo,
        
        /// <remarks/>
        HardCancel,
        
        /// <remarks/>
        Pause,
        
        /// <remarks/>
        Renew,
        
        /// <remarks/>
        Resume,
        
        /// <remarks/>
        SoftCancel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class TransactionErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestGetDownloadLinksItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string languageField;
        
        private string alphabetField;
        
        private string regionField;
        
        private string rebrandingCodeField;
        
        private PlatformEnum platformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
                this.RaisePropertyChanged("Alphabet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RebrandingCode {
            get {
                return this.rebrandingCodeField;
            }
            set {
                this.rebrandingCodeField = value;
                this.RaisePropertyChanged("RebrandingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PlatformEnum Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("Platform");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestGetInfoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private SubscriptionInfoType infoSectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubscriptionInfoType InfoSection {
            get {
                return this.infoSectionField;
            }
            set {
                this.infoSectionField = value;
                this.RaisePropertyChanged("InfoSection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum SubscriptionInfoType {
        
        /// <remarks/>
        Subscription,
        
        /// <remarks/>
        SubscriptionUsage,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Subscription, SubscriptionUsage")]
        SubscriptionSubscriptionUsage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestPauseItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime pauseTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime PauseTime {
            get {
                return this.pauseTimeField;
            }
            set {
                this.pauseTimeField = value;
                this.RaisePropertyChanged("PauseTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestResumeItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestHardCancelItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestSoftCancelItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestRenewItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestActivateItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime startTimeField;
        
        private string endTimeField;
        
        private string licenseCountField;
        
        private string productIdField;

        private bool userIgnoreField;
        
        private ActivationTypeEnum activationTypeField;
        
        public SubscriptionRequestActivateItem() {
            this.licenseCountField = "1";
            this.activationTypeField = ActivationTypeEnum.Standard;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("UnitId");
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UserIgnore
        {
            get
            {
                return this.userIgnoreField;
            }
            set
            {
                this.userIgnoreField = value;
                this.RaisePropertyChanged("userIgnore");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string LicenseCount {
            get {
                return this.licenseCountField;
            }
            set {
                this.licenseCountField = value;
                this.RaisePropertyChanged("LicenseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ActivationTypeEnum.Standard)]
        public ActivationTypeEnum ActivationType {
            get {
                return this.activationTypeField;
            }
            set {
                this.activationTypeField = value;
                this.RaisePropertyChanged("ActivationType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum ActivationTypeEnum {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Secondary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string transactionIdField;
        
        private object[] subscriptionRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Activate", typeof(SubscriptionRequestActivateItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GetDownloadLinks", typeof(SubscriptionRequestGetDownloadLinksItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GetInfo", typeof(SubscriptionRequestGetInfoItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HardCancel", typeof(SubscriptionRequestHardCancelItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Pause", typeof(SubscriptionRequestPauseItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Renew", typeof(SubscriptionRequestRenewItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resume", typeof(SubscriptionRequestResumeItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SoftCancel", typeof(SubscriptionRequestSoftCancelItem), IsNullable=false)]
        public object[] SubscriptionRequest {
            get {
                return this.subscriptionRequestField;
            }
            set {
                this.subscriptionRequestField = value;
                this.RaisePropertyChanged("SubscriptionRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string transactionIdField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionError", typeof(SubscriptionResponseErrorCollection), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionResponse", typeof(SubscriptionResponseItemCollection), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("TransactionError", typeof(TransactionErrorType), Order=2)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
        public BLL.KL_API.AccessInfo AccessInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", Order=0)]
        public BLL.KL_API.SubscriptionRequestContainer SubscriptionRequestContainer;
        
        public SubscriptionRequestRequest() {
        }
        
        public SubscriptionRequestRequest(BLL.KL_API.AccessInfo AccessInfo, BLL.KL_API.SubscriptionRequestContainer SubscriptionRequestContainer) {
            this.AccessInfo = AccessInfo;
            this.SubscriptionRequestContainer = SubscriptionRequestContainer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", Order=0)]
        public BLL.KL_API.SubscriptionResponseContainer SubscriptionResponseContainer;
        
        public SubscriptionRequestResponse() {
        }
        
        public SubscriptionRequestResponse(BLL.KL_API.SubscriptionResponseContainer SubscriptionResponseContainer) {
            this.SubscriptionResponseContainer = SubscriptionResponseContainer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KasperskySubscriptionServicePortTypeChannel : BLL.KL_API.KasperskySubscriptionServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KasperskySubscriptionServicePortTypeClient : System.ServiceModel.ClientBase<BLL.KL_API.KasperskySubscriptionServicePortType>, BLL.KL_API.KasperskySubscriptionServicePortType {
        
        public KasperskySubscriptionServicePortTypeClient() {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KasperskySubscriptionServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.KL_API.SubscriptionRequestResponse BLL.KL_API.KasperskySubscriptionServicePortType.SubscriptionRequest(BLL.KL_API.SubscriptionRequestRequest request) {
            return base.Channel.SubscriptionRequest(request);
        }
        
        public BLL.KL_API.SubscriptionResponseContainer SubscriptionRequest(BLL.KL_API.AccessInfo AccessInfo, BLL.KL_API.SubscriptionRequestContainer SubscriptionRequestContainer) {
            BLL.KL_API.SubscriptionRequestRequest inValue = new BLL.KL_API.SubscriptionRequestRequest();
            inValue.AccessInfo = AccessInfo;
            inValue.SubscriptionRequestContainer = SubscriptionRequestContainer;
            BLL.KL_API.SubscriptionRequestResponse retVal = ((BLL.KL_API.KasperskySubscriptionServicePortType)(this)).SubscriptionRequest(inValue);
            return retVal.SubscriptionResponseContainer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.KL_API.SubscriptionRequestResponse> BLL.KL_API.KasperskySubscriptionServicePortType.SubscriptionRequestAsync(BLL.KL_API.SubscriptionRequestRequest request) {
            return base.Channel.SubscriptionRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLL.KL_API.SubscriptionRequestResponse> SubscriptionRequestAsync(BLL.KL_API.AccessInfo AccessInfo, BLL.KL_API.SubscriptionRequestContainer SubscriptionRequestContainer) {
            BLL.KL_API.SubscriptionRequestRequest inValue = new BLL.KL_API.SubscriptionRequestRequest();
            inValue.AccessInfo = AccessInfo;
            inValue.SubscriptionRequestContainer = SubscriptionRequestContainer;
            return ((BLL.KL_API.KasperskySubscriptionServicePortType)(this)).SubscriptionRequestAsync(inValue);
        }
    }
}
