<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Termos.aspx.cs" Inherits="KL_Vendas.Termos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Termos de Venda</title>
    <link rel="stylesheet" href="css/bootstrap-3.3.7.min.css"/>
      <link rel="stylesheet" href="css/FontMuseoSans.css"/>
    <link rel="stylesheet" href="css/styleC.css" type="text/css" media="all" />
    <link rel="icon" type="image/png" href="img/FavIcon_Linktel.ico" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <div class="dr_logo col-md-2 col-sm-2 col-xs-5">
            <img src="images/nav/logo_b.png" width="100%"/>
            </div>
        </div>
        <div class="container-fluid breadcrumbContainer">&#160;</div>

        <div xmlns="http://www.w3.org/1999/xhtml">
            <div class="dr_Content" id="dr_ThankYou">
                <div class="TYContent">
                    
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
<h1>Termos de venda:</h1>
1.ESCOPO E APLICAÇÃO<br />
<br />1.1ESTES TERMOS E CONDIÇÕES DE VENDAS (“TERMOS”) APLICAM-SE A TODAS AS OFERTAS, VENDAS E COMPRAS DE PRODUTOS (INCLUINDO, SEM LIMITAR-SE, HARDWARE E/OU SOFTWARE) (“PRODUTOS”) OU SERVIÇOS (“SERVIÇOS”) QUE SÃO VENDIDOS ATRAVÉS DO WEBSITE NO QUAL PUBLICAMOS ESTES TERMOS (“SITE”) POR: (A) NÓS, ITAILERS GESTAO EMPRESARIAL E MARKETING LTDA. (REFERÊNCIAS A “NÓS”, “CONOSCO” OU “NOSSO” DE ACORDO COM A ELABORAÇÃO CORRESPONDENTE) O VENDEDOR, PARA (B) VOCÊ, O COMPRADOR (REFERÊNCIAS A "VOCÊ" OU “SEU” DE ACORDO COM A ELABORAÇÃO CORRESPONDENTE).
<br />1.2TODAS AS COMPRAS SÃO FINAIS, NÃO CANCELÁVEIS E NÃO REEMBOLSÁVEIS, EXCETO SE ESPECIFICADO NA POLÍTICA DE DEVOLUÇÕES E LEGISLAÇÃO APLICÁVEIS.2. OFERTA, RECONHECIMENTO E ACEITAÇÃO
<br />2.1 Qualquer preço, cotação e descrição feitos ou descritos neste Site estão sujeitos à disponibilidade, não constituem uma oferta e podem ser retirados ou revisados a qualquer momento antes de nossa aceitação expressa de seu pedido (como descrito a seguir). 2.2 Apesar de todos os nossos esforços para garantir que todos os itens exibidos no Site estejam disponíveis, não podemos garantir que todos os itens estejam no estoque ou imediatamente disponíveis quando você enviar seu pedido. Podemos recusar seu pedido (sem responsabilidade legal) se não pudermos processá-lo ou atendê-lo. Caso este seja o caso, reembolsaremos qualquer pagamento prévio que tenha sido feito pelo item.2.3 Um pedido enviado por você constitui uma oferta sua para conosco a fim de comprar Produtos ou Serviços nestes Termos e está sujeito a nossa subseqüente aceitação.2.4 Antes dessa aceitação, um reconhecimento automático por e-mail de seu pedido pode ser gerado. Observe que este reconhecimento automático não constitui uma aceitação formal de seu pedido.2.5 Nossa aceitação de seu pedido torna-se válida e o contrato concluído quando essa oferta é expressamente aceita pelo nosso envio de seu pedido/início dos Serviços e a aceitação de seu cartão de crédito ou outro pagamento ("Aceitação"). 2.6 Pode ser que mantenhamos registros de pedidos recebidos, reconhecimentos, aceitações e outros registros de contrato por um período razoável após a Aceitação. Podemos fornecer cópias a você mediante solicitação escrita; entretanto, assegure-se de imprimir uma cópia de todos estes documentos e destes Termos para seu próprio arquivo.3. SUAS DECLARAÇÕES 
<br />3.1 Você declara que as informações que forneceu ao colocou em seu pedido estão precisamente atualizadas e são suficientes para que atendamos seu pedido.3.2 Você é responsável por manter e atualizar imediatamente suas informações de conta conosco quanto à precisão e totalidade e por mantê-las (e qualquer senha dada a você para acessar o Site e/ou de compra de Produtos) protegidas contra acesso não-autorizado.3.3 A menos que acordado em contrário ou requerido por lei aplicável, qualquer garantia fornecida com relação aos Produtos ou Serviços é aplicável a você apenas, compreendendo que seja um usuário e não um revendedor destes Produtos ou Serviços. 3.4 Nenhuma garantia, compromisso ou qualquer outra obrigação deve ser presumida por você ou em seu nome ou em nome de um fabricante de Produto, licenciado ou fornecedor sem nosso prévio e expresso consentimento escrito.4. PREÇO E TERMOS DE PAGAMENTO (OBSERVAÇÃO: NÃO PODEMOS CONFIRMAR PREÇOS ANTES DA ACEITAÇÃO DE SEU PEDIDO)
<br />4.1 Os preços a serem pagos por Produtos ou Serviços são os vigentes no momento da remessa ou entrega, a menos que expressamente acordado de outra forma. Os preços podem ser indicados no Site ou em um reconhecimento de pedido. No entanto, no caso de qualquer discrepância, o preço mandatório será o preço comunicado a você na nossa Aceitação. 4.2 Reservamo-nos o direito de, a qualquer momento, antes de nossa Aceitação, retirar qualquer desconto e/ou revisar preços para considerar aumentos nos custos incluindo (sem limitar-se) custos de qualquer material, transporte, mão-de-obra ou o aumento ou imposição de qualquer imposto, encargos ou outro tributo e qualquer variação nas taxas de câmbio. Reservamo-nos o direito também de comunicá-lo sobre erros nas descrições do Produto ou erros no preço antes do envio do produto. Neste caso, se decidir continuar com o cumprimento do pedido, você aceita que o Produto ou Serviço será fornecido de acordo com essa descrição revisada ou preço corrigido.4.3 Os locais onde entregamos nossos Produtos e fornecemos nossos Serviços estão listados no Site ("Território"). A menos que especificado em contrário, os preços cotados: 
<br />
<br />4.3.1 Não incluem custos de embarque ou de transporte para o local de entrega acordado dentro do Território (as taxas são especificadas no Site); e4.3.2 Não incluem ICMS ou outro imposto ou tributo o qual (quando aplicável) deve ser agregado ao valor a ser pago;neste sentido, você concorda em pagar os impostos, o embarque ou o transporte dos Produtos já que esses custos são especificados por nós no Site ao enviar seu pedido de compra.
<br />
<br />4.4 O pagamento deve ocorrer antes da entrega e pelos métodos indicados no Site (e por nenhum outro meio a menos que tenhamos concordado previamente).4.5 Exceto se especificado expressamente em qualquer outro Item destes Termos ou do Site, o pagamento será completo, independente de qualquer alegação de entrega parcial ou defeitos.4.6 Debitaremos os cartões de crédito ou de débito no embarque do Produto ou no início dos Serviços. Reservamo-nos o direito de verificar os pagamentos de cartão de crédito ou de débito antes da Aceitação.4.7 Quando o pagamento for faturado, cada nota fiscal deve ter data de vencimento e ser executada em um prazo de 30 (trinta) dias da data da nota fiscal pertinente. Se em qualquer momento você não efetuar o pagamento de qualquer montante devido na data de vencimento pertinente, podemos, através de comunicado, declarar todos os montantes faturados não pagos naquela data imediatamente vencidos e a serem pagos.4.8 Nenhum pedido reconvencional ou acordo pode ser deduzido de qualquer pagamento devido sem nosso consentimento escrito. Podemos também tomar providências contra você com relação ao preço dos Produtos a qualquer momento, após o atraso do pagamento, mesmo que a propriedade destes Produtos ainda não tenha sido transferida a você.4.9Qualquer ampliação do crédito dado a você pode ser modificada ou retirada a qualquer momento. Juros serão cobrados sobre os montantes atrasados acumulados diariamente até o montante máximo permitido de acordo com a legislação vigente a partir da data de vencimento do pagamento até que recebamos o montante total (seja antes ou depois de decisão judicial). Você deverá nos indenizar mediante solicitação sobre qualquer despesa extra com relação à recuperação dos montantes devidos.5. RESCISÃO
<br />5.1 Se você abrir falência ou entrar em concordata com seus credores ou se uma ordem judicial para liquidação for expedida em seu nome ou se tomar ou sofrer uma ação semelhante em conseqüência de um débito ou, ainda, (i) se tivermos motivos para crer que não está apto a pagar seus débitos em seus vencimentos; (ii) se não pagar algum montante até a data do vencimento; e (iii) se quebrar qualquer um destes Termos então, sem dano a qualquer outro direito nosso, podemos:- 
<br />
<br />5.1.1 Interromper qualquer Produto em trânsito; e/ou
<br />5.1.2 Suspender entregas futuras de Produto; e/ou
<br />5.1.3 Interromper ou suspender o fornecimento dos Serviços; e/ou
<br />5.1.4 Através de comunicado escrito, rescindir seu pedido e todo ou qualquer outro contrato entre nós e você.
<br />
<br />6. ENTREGA E RISCO
<br />6.1 Os cronogramas/datas de entrega especificados no Site, em qualquer reconhecimento de pedido, aceitação ou qualquer outro lugar são apenas estimativas. Embora trabalhemos para atender tais cronogramas ou datas, não nos responsabilizamos por despachar Produtos e/ou iniciar Serviços em uma data ou datas em particular e não devemos ser responsabilizados por atrasos ou falha em cumpri-los.6.2 A entrega deve ser para um endereço válido dentro do Território informado por você e sujeito à Aceitação ("Endereço de Entrega"). Você deve verificar o Endereço de Entrega em qualquer reconhecimento ou aceitação que forneçamos e comunicar-nos imediatamente sobre erros ou omissões. Reservamo-nos o direito de cobrá-lo por qualquer custo adicional decorrente das mudanças que fizer no Endereço de Entrega após o seu envio de um pedido.6.3 Se recusar ou não receber os produtos fornecidos de acordo com estes Termos, qualquer risco de perda ou dano aos Produtos serão transferidos a você e sem prejuízo de outros direitos ou remédios que tenhamos:
<br />
<br />6.3.1 Teremos o direito ao pagamento total e imediato pelos Produtos ou Serviços entregues e também para efetuar a entrega por qualquer meio que considerarmos apropriado ou para armazenar Produtos a seu risco;
<br />6.3.2 Você deverá ser responsável pelo pagamento, mediante solicitação, de todos os custos de armazenamento de Produto e qualquer custo adicional incorridos como resultado de tal recusa ou falha em aceitar a entrega;
<br />6.3.3 Teremos o direito de, em 30 dias após a data acordada de entrega do(s) Produto(s), dispormos dos Produtos do modo que determinarmos e podemos iniciar procedimento de cobrança dos valores devidos por você. 
<br />
<br />6.4 Você terá o direito de recusar os Produtos no todo ou em parte por motivo de entrega parcial, ou por qualquer outro motivo, desde que nos notifique por escrito sobre qualquer reclamação em um prazo de 7 dias úteis a contar de sua assinatura ou do ato de recebimento do produto ou serviço.6.5 Nos casos em que entregarmos Produtos em parcelas, cada parcela constitui um contrato separado e qualquer falha em uma ou mais parcelas não lhe dará o direito de repudiar o contrato como um todo ou cancelar qualquer parcela subseqüente.6.6 Exceto se estabelecido de forma diversa nestes Termos, o risco de perda ou de dano aos Produtos é transferido a você mediante a entrega do Produto ou quando este é transferido para sua posse ou, ainda, por qualquer transportador ou transporte fornecido por você, o que ocorrer primeiro.7. RECUSA, DANO OU PERDA EM TRÂNSITO
<br />7.1 Exceto pelo estabelecido acima ou de acordo com as Políticas de Devolução aplicáveis e sujeito a qualquer direito que tenha de acordo com a legislação vigente que não pode ser excluído ou limitado por estes Termos:
<br />
<br />7.1.1Não nos responsabilizaremos e você não terá direito de recusar os Produtos ou Serviços, exceto por:
<br />
<br />(a) dano ou perda dos Produtos ou de qualquer parte deles em trânsito (no caso em que os Produtos são transportados por nosso próprio transporte ou por uma transportadora em nosso nome) quando nos for notificado em um prazo de 5 dias úteis desde o recebimento dos Produtos;
<br />(b) defeitos nos Produtos (não sendo defeitos causados por algum ato, negligência ou dolo de sua parte) comunicado por escrito em um prazo de 30 dias do recebimento dos Produtos; ou
<br />(c) desempenho defeituoso dos Serviços (não sendo defeitos causados por algum ato, negligência ou dolo de sua parte) comunicado a nós por escrito em um prazo de 5 dias da data em que o defeito se tornou aparente.
<br />
<br />
<br />7.1.2 não nos responsabilizaremos por qualquer dano ou perda decorrente de instalação incorreta dos Produtos; do uso dos Produtos em relação a outro equipamento defeituoso, impróprio ou instalado incorretamente; sua negligência; uso indevido ou uso de qualquer modo inconsistente com as especificações ou instruções do fabricante.7.1.3 No caso de não ser determinado vício referente a defeito no Produto sanado no prazo máximo de 30 dias, você poderá exigir, alternativamente e à sua escolha: 
<br />
<br />(i) a substituição do Produto mediante a devolução do Produto por outro da mesma espécie; (ii) a restituição imediata da quantia paga, monetariamente atualizada, sem prejuízo de eventuais perdas e danos; ou;(iii) o abatimento proporcional do preço.
<br />
<br />8. SOFTWARE
<br />8.1 Quando o Produto fornecido for ou incluir software (“Software”), este Software é licenciado por nós ou por um proprietário/outorgante de licença sujeito ao contrato de licença de usuário final pertinente ou outros termos de licença incluídos no Software (“Termos de Licença”) e/ou Produto. Além disso:
<br />
<br />8.1.1 O Software não pode ser copiado, adaptado, traduzido, disponibilizado, distribuído, variado, modificado, desmontado, descompilado, sofrer engenharia reversa ou ser combinado com qualquer outro software, exceto pelo (i) que é permitido nos Termos da Licença, ou (ii) a legislação vigente obrigar expressamente um direito que não pode ser legalmente excluído por contrato.8.1.2 Exceto pelo disposto por qualquer um dos Termos de Licença aplicáveis, seus direitos de devolução e/ou de reembolso sob estes Termos e qualquer Política de Devolução aplicável, não são aplicáveis caso você abra a embalagem do Software e/ou quebre o selo de licença e/ou use o Software.8.1.3 Exceto pelo expressamente disposto por nós por escrito ou de acordo com os Termos de Licença pertinentes, o Software é fornecido ‘como está’ sem qualquer garantia, termos de qualidade, adequação para uso, desempenho ou correspondência com a descrição e não oferecemos quaisquer garantias com relação à instalação, configuração ou correção de erro/defeito do Software. Recomendamos que consulte os Termos de Licença para determinar seus direitos com o fabricante, outorgante da licença ou fornecedor do Software.
<br />
<br />
<br />9. LIMITAÇÃO DE RESPONSABILIDADE
<br />9.1 PELA DISPOSIÇÃO MÁXIMA LEGALMENTE PERMITIDA, ESTEJAMOS OU NÃO CIENTES OU INFORMADOS DA POSSIBILIDADE DE DANOS, E INDEPENDENTE DOS REMÉDIOS LIMITADOS DESTE FALHAREM OU NÃO EM CUMPRIR SEUS FINS ESSENCIAIS, NOSSA RESPONSABILIDADE CONJUNTA (SEJA POR QUEBRA DE CONTRATO, ATO ILÍCITO OU QUALQUER OUTRA TEORIA LEGAL) NÃO DEVE JAMAIS EXCEDER O CUSTO DOS PRODUTOS PEDIDOS POR VOCÊ E QUE ESTEJAM MAIS PRÓXIMOS DE SEUS DANOS. VOCÊ ENTENDE E CONCORDA QUE O PREÇO PAGO POR VOCÊ NOS PRODUTOS ENTREGUES E SERVIÇOS FORNECIDOS PELA DIGITAL RIVER ESTÁ DIRETAMENTE RELACIONADO COM OS RISCOS ENVOLVIDOS NESTA TRANSAÇÃO, BEM COMO COM AS ANÁLISES DE VIABILIDADE REALIZADAS A FIM DE LANÇAR TAIS PRODUTOS NO MERCADO. DESTA FORMA, AS LIMITAÇÕES DE RESPONSABILIDADE ESTABELECIDAS NESTE ITEM CONSTITUEM ELEMENTOS ESSENCIAIS DESTES TERMOS DE VENDA SENDO QUE, NO CASO DE AUSÊNCIA DE TAL LIMITAÇÃO, OS PREÇOS E DEMAIS DISPOSIÇÕES DESTES TERMOS SERIAM SUBSTANCIALMENTE DIFERENTES.
<br />10. DIREITOS DE TERCEIROS
<br />10.1 Você deverá indenizar-nos contra qualquer e toda obrigação, reivindicações e custos incorridos ou feitos contra nós decorrentes direta ou indiretamente do desempenho dos Serviços ou execução de qualquer trabalho relativos aos Produtos ou para os Produtos, nos quais isto foi feito de acordo com seus requisitos ou especificações (ou de seus representantes e que tenham causado uma infração ou uma alegação de infração de qualquer direito de propriedade de terceiros.
<br />10.2 De acordo com as disposições plenas de lei e exceto onde expressamente estabelecido em qualquer um dos Termos de Licença ou algum outro lugar, não teremos obrigações para com você caso os Produtos ou Serviços infrinjam ou sejam acusados de infringir os direitos de propriedade de terceiros. No caso dos Produtos serem ou poderem ser sujeitos a patente, copyright, direito de banco de dados, projeto registrado, marca registrada ou outros direitos de terceiros, você deve consultar os termos relevantes do fabricante e/ou do outorgante da licença/proprietário do Produto. Devemos ser obrigados a transferir para você apenas os direitos ou títulos que tivermos.
<br />11. GARANTIA “COMO ESTÁ” NO GERAL – INDEPENDENTE DE DECLARAÇÕES DE GARANTIA SEPARADAS ENVIADAS PELO FABRICANTE COM OS PRODUTOS 
<br />11.1 Todas as especificações, ilustrações, desenhos, particularidades, dimensões, dados de desempenho e outras informações do Produto no Site ou disponibilizados por nós têm por objetivo representar não mais do que uma ilustração geral dos Produtos e não constituem uma garantia ou representação nossa de que os Produtos estarão de acordo com esta ilustração. Você deve consultar as especificações do fabricante ou a documentação de garantia para determinar seus direitos e respectivos remédios.
<br />11.2 Você terá o benefício da garantia do fabricante, do outorgante da licença ou do fornecedor com os Produtos fornecidos e deve consultar a documentação pertinente fornecida com o Produto, referente a tal garantia. (Se aplicável, uma Política de Devolução também pode estabelecer procedimentos aplicáveis a reparos ou substituições de Produtos defeituosos entregues).
<br />11.3 Seus direitos de reparo ou de substituição de qualquer Produto ou de qualquer parte ou partes dele que sejam considerados defeituosos serão (exceto se acordado em contrário) negados ou considerados nulos quando: 
<br />
<br />11.3.1Os Produtos foram consertados ou alterados por pessoas que não sejam o fabricante, nós ou qualquer representante autorizado; e/ou11.3.2 o Produto ou Produtos defeituosos não foram devolvidos junto com todos os detalhes por escrito dos defeitos alegados em um prazo de 30 dias a contar da data em que os Produtos foram entregues; e/ou11.3.2 o Produto ou Produtos defeituosos não foram devolvidos junto com todos os detalhes por escrito dos defeitos alegados em um prazo de 30 dias a contar da data em que os Produtos foram entregues; e/ou11.3.3 Os defeitosforem decorrentes de (no todo ou em parte) manuseio incorreto, uso, armazenamento, manutenção ou instalação indevidos, ou falha em observar qualquer instrução do fabricante ou outras orientações emitidas ou disponibilizadas por nós com relação aos Produtos entregues.
<br />
<br />
<br />11.4 EXCETO SE EXPRESSO EM CONTRÁRIO NESTA CLÁUSULA 11, NÃO DAMOS DECLARAÇÕES OU GARANTIAS EXPRESSAS E DESQUALIFICAMOS TODAS AS GARANTIAS E REPRESENTAÇÕES IMPLÍCITAS, INCLUINDO, SEM LIMITAR-SE, AS GARANTIAS IMPLÍCITAS DE PADRÃO DE QUALIDADE DO PRODUTO, ADEQUAÇÃO PARA UM FIM EM PARTICULAR E NÃO-INFRAÇÃO. ESTES TERMOS DECLARAM SEUS REMÉDIOS ÚNICOS E EXCLUSIVOS.
<br />12. CONSENTIMENTO, DIREITOS ALFANDEGÁRIOS E EXPORTAÇÃO
<br />12.1 Se qualquer licença ou consentimento de qualquer governo ou outra autoridade for requerida para a aquisição, transporte ou uso dos Produtos por você, a obtenção de tal licença ou consentimento correrá as suas próprias custas e, se necessário, você deverá exibir os documentos de comprovação, se assim solicitarmos. Caso não proceda dessa forma, isso não lhe dará o direito de reter ou atrasar o pagamento do preço. Qualquer despesa adicional ou taxa incorrida por nós resultante de tal falha deverá ser coberta por você.
<br />12.2 Os produtos licenciados ou vendidos para você de acordo com estes Termos podem estar sujeitos à legislação de controle de exportação no Território ou outra jurisdição pertinente onde ocorrer a entrega ou onde houver o uso. Você será responsável por cumprir tais leis e não fará nada para violá-las. 
<br />12.3 Os itens que entram na Área Econômica Européia (EEA) do exterior por um determinado valor podem estar sujeitos a taxas alfandegárias (ex. onde os custos estão acima do valor de importação pessoal permitido). Você pode estar sujeito a taxas alfandegárias, impostos e tributos de importação, tributos, quando o Produto atinge o destino especificado. Qualquer despesa adicional para liberação na alfândega ou impostos ou tributos de importação devem ser pagos por você, uma vez que não temos controle sobre quais são estas despesas. Entre em contato com o escritório de alfândega local na jurisdição pertinente para obter mais informações sobre as políticas ou tributos da alfândega.
<br />12.4Ao fazer uma Compra, poderá ser exibida a opção para pagamento antecipado ou não das taxas de importação e obrigações alfandegárias que podem ser cobradas pelo país de destino, bem como qualquer taxa de despesa, taxas de adiantamento ou taxas similares que podem ser impostas pelo embarcador, corretor, pela autoridade aduaneira do país de destino ou por outra parte (coletivamente, "Custos de importação"). Empenharemos nossos esforços comercialmente razoáveis para estimar o valor dos Custos de importação (uma estimativa, a "Estimativa"). Entretanto, a Estimativa pode ser maior ou menor do que o valor final efetivo dos Custos de importação devidos e pagáveis. Não temos controle sobre os Custos de importação e nem sempre é possível prever com 100% de precisão quais serão os custos finais reais. Para maior exatidão, você deve entrar em contato com a agência aduaneira local para obter mais informações sobre as tarifas de importação e as obrigações alfandegárias que podem ser aplicáveis à sua Compra. 
<br />
<br />12.4.1Se optar por fazer o pagamento antecipado dos Custos de importação, você concorda e aceita que (a) os Custos de importação efetivos podem ser maiores ou menores do que a Estimativa e (b) NÃO será solicitado que você pague mais dinheiro TAMPOUCO receberá qualquer reembolso caso os Custos de importação efetivos sejam diferentes da Estimativa.12.4.2Se optar por fazer o pagamento antecipado dos Custos de importação na Estimativa, você concorda e aceita que a parte recebedora no país do de destino final do produto continua sendo responsável por fazer a entrada correta, declarando a mercadoria junto às autoridades aduaneiras apropriadas, pagando quaisquer obrigações alfandegárias/taxas/impostos/despesas e/ou atendendo quaisquer requisitos adicionais relacionados à importação. Entre em contato com as autoridades aduaneiras locais no país competente para obter mais informações sobre os requisitos, procedimentos, direitos, taxas, impostos ou outros encargos que poderão incidir sobre o Produto.12.4.3Se optar por fazer o pagamento antecipado dos Custos de importação, você concorda e aceita que (i) os Custos de importação efetivos pode ser maiores ou menores do que a Estimativa; (ii) você (e não a Digital River, o corretor, o embarcador, o fornecedor ou qualquer outro terceiro) deverá arcar com a responsabilidade pelo pagamento de todos os Custos de importação efetivos; (iii) caso outra entidade, não você, deverá pagar por parte ou todos os Custos de importação em seu nome para efetivar o despacho aduaneiro, você reembolsará totalmente (mediante solicitação) tal entidade pelos Custos de importação efetivos pagos em seu nome; e (iv) o seu não pagamento dos Custos de importação oportunamente poderá causar atrasos além de nossa estimativa de entrega original, como também o expõe a riscos por obrigações em potencial em relação a tarifas e outras taxas.
<br />
<br />13. NOTIFICAÇÕES13.1 Qualquer notificação ou outra comunicação com relação ao nosso contrato podem ser realizadas enviando-as em mãos, registradas, por e-mail, ao último endereço e contato que uma parte comunicou à outra por escrito. Este será também o endereço para o serviço de procedimentos legais como descrito por lei. Nosso endereço para comunicação é Itailers Gestão Empresarial e Marketing localizado na Rua Doutor Gabriel Piza, 577 - São Paulo SP, Brasil, e nosso e-mail é falecom@antiviruslinktel.com.br. 
<br />
<br />Exceto se estabelecido acima com relação ao cancelamento dos pedidos do cliente, tais notificações ou comunicações (quando devidamente endereçadas) devem ser consideradas recebidas:
<br />
<br />13.1.1 Com relação à entrega em mãos, na data da entrega no endereço pertinente (ou se não for um dia útil, o primeiro dia útil subseqüente);
<br />13. Se enviado 5 dias úteis após a data de envio;
<br />
<br />13.1.2 Se enviado por e-mail, o que for mais recente (i) o reconhecimento do e-mail pelo destinatário como recebido; (ii) recebimento do emissor de uma mensagem automática indicando a entrega bem-sucedida ou a abertura do e-mail; ou (iii) o período de 48 horas após a transmissão, desde que o emissor não tenha recebido uma notificação de falha de transmissão. 
<br />
<br />14. INFORMAÇÕES PESSOAIS E SUA PRIVACIDADE
<br />14.1 Observaremos as leis de proteção de dados vigentes e não usaremos informações que usem ou possam ser usadas para identificar você pessoalmente ("Dados Pessoais") conforme estabelecido em nossa Política de Privacidade em Política de Privacidade ("Política de Privacidade"). Ao enviar seus Dados Pessoais com relação ao seu pedido, você autoriza que os Dados Pessoais sejam processados para cumprir seu pedido de acordo com tal Declaração de Privacidade.
<br />14.2 Com relação à segurança dos pedidos colocados conosco:
<br />
<br />14.2.1 Nosso software de servidor protegido criptografa todos os seus Dados Pessoais incluindo número e nome de cartão de crédito ou de débito e endereço são protegidos pelo sistema de pagamento utilizado a Pagar.me. 
<br />
<br />15. GERAL 
<br />15.1 Você não deve atribuir, transferir, cobrar ou atualizar ou pretender atribuir, transferir, cobrar ou atualizar seus direitos de acordo com estes Termos. Qualquer pretensão de atribuição deve ser nula ou inválida.
<br />15.2Não devemos ser obrigados para com você ou acusados com relação a quebra de contrato quanto a qualquer perda ou dano que possa ser sofrido como um resultado direto ou indireto por estarmos proibidos, impossibilitados ou atrasados no desempenho por circunstâncias além de nosso controle incluindo (sem limitar-se) qualquer força maior, guerra, ato terrorista, tumulto, comoção civil, ação do governo, explosão, incêndio, inundação, tempestade, acidente, greve, greve promovida pelo empregador, disputa comercial ou distúrbio da força de trabalho, parada de fábrica ou de máquinas, interrupção no fornecimento de energia, comunicações de Internet ou outros materiais, caso no qual podemos decidir cancelar seu pedido e reembolsá-lo quanto a eventuais pagamentos feitos.
<br />15.3 Seu reconhecimento destes Termos substitui e cancela todos os contratos anteriores, acordos e acordos de trabalho, sejam eles verbais ou escritos, expressos ou implícitos, entre nós. Estes Termos prevalecem sobre outros termos contidos ou mencionados em outros lugares ou implícitos por comércio, alfândega ou curso de negócios. Qualquer termo ou condição contrários são por este excluídos nos termos plenos permitidos por lei. De acordo com as disposições gerais permitidas por lei, reservamo-nos o direito de modificar estes Termos mediante comunicação prévia a você com efeito no futuro – sujeito ao seu direito de recusar, por meio de comunicado escrito, nossas modificações nestes Termos com relação a qualquer pedido para o qual a Aceitação, mas não cumprimento, tenha ocorrido.
<br />15.4 Nenhum relaxamento, prazo de tolerância, atraso ou indulgência por você ou por nós no cumprimento destes Termos ou na concessão de tempo por qualquer parte à outra deve prejudicar ou restringir tais direitos e poderes.
<br />15.5 Nenhuma renúncia de qualquer termo ou condição destes Termos deve ser efetiva a menos que estabelecida por escrito e assinada por nós. A renúncia a qualquer quebra de qualquer um dos Termos não deve ser considerada uma renúncia das quebras de contrato ou termos subseqüentes.
<br />15.6 Caso por qualquer motivo determinarmos ou uma Corte de jurisdição competente determinar que qualquer disposição ou parte destes Termos seja ilegal, não obrigatória ou inválida de acordo com a legislação vigente em uma jurisdição em particular:
<br />
<br />15.6.1 Estes Termos não serão afetados em outras jurisdições na medida em que a determinação ou descoberta não tenha aplicação; e
<br />15.6.2 Na jurisdição pertinente, o remanescente destes Termos (nos termos totais permitidos por lei) continuarão em vigor e em efeito.
<br />16. LEGISLAÇÃO APLICÁVEL 
<br />16.1 A validade e o desempenho da elaboração destes Termos devem ser regidos por Lei Brasileira e as partes se submetem à jurisdição exclusiva de Cortes Brasileiras, no caso de procedimentos legais decorrentes de qualquer disputa; 
<br />16.2 O idioma de qualquer procedimento de resolução de disputa ou qualquer processo judicial será o Português.
                      </div>  
                </div>
            </div>
<div id="dr_TCFooter">
                        <p class="dr_legalResellerStatement"><a class="dr_aboutDigitalRiver" href="AboutUs.aspx"  target="_blank">Itailers</a>, é o distribuidor e vendedor autorizado de licenças, software, produtos, serviços e outros itens oferecidos nessa loja.</p>
                        </div>


        </div>

    </form>
</body>
</html>
