//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", ConfigurationName="UPI.KasperskySubscriptionServicePortType")]
    public interface KasperskySubscriptionServicePortType
    {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação SubscriptionRequest não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.kaspersky.com/services/subscription/subscriptionRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPI.SubscriptionRequestResponse SubscriptionRequest(UPI.SubscriptionRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.kaspersky.com/services/subscription/subscriptionRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<UPI.SubscriptionRequestResponse> SubscriptionRequestAsync(UPI.SubscriptionRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class AccessInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseErrorCollection
    {
        
        private ResponseItemErrorType[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivateError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetDownloadLinksError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetInfoError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HardCancelError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PauseError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RenewError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ResumeError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SoftCancelError", typeof(ResponseItemErrorType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ResponseItemErrorType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class ResponseItemErrorType
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", IncludeInSchema=false)]
    public enum ItemsChoiceType1
    {
        
        /// <remarks/>
        ActivateError,
        
        /// <remarks/>
        GetDownloadLinksError,
        
        /// <remarks/>
        GetInfoError,
        
        /// <remarks/>
        HardCancelError,
        
        /// <remarks/>
        PauseError,
        
        /// <remarks/>
        RenewError,
        
        /// <remarks/>
        ResumeError,
        
        /// <remarks/>
        SoftCancelError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollection
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activate", typeof(SubscriptionResponseItemCollectionActivate), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetDownloadLinks", typeof(SubscriptionResponseItemCollectionGetDownloadLinks), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetInfo", typeof(SubscriptionResponseItemCollectionGetInfo), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HardCancel", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Pause", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Renew", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Resume", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SoftCancel", typeof(BaseResponseItemType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionActivate
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string activationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActivationCode
        {
            get
            {
                return this.activationCodeField;
            }
            set
            {
                this.activationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionGetDownloadLinks
    {
        
        private GetDownloadLinksInfo[] downloadLinksField;
        
        private PlatformEnum platformField;
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DownloadLink", IsNullable=false)]
        public GetDownloadLinksInfo[] DownloadLinks
        {
            get
            {
                return this.downloadLinksField;
            }
            set
            {
                this.downloadLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PlatformEnum Platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class GetDownloadLinksInfo
    {
        
        private string urlField;
        
        private string languageField;
        
        private string alphabetField;
        
        private string regionField;
        
        private string rebrandingCodeField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alphabet
        {
            get
            {
                return this.alphabetField;
            }
            set
            {
                this.alphabetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RebrandingCode
        {
            get
            {
                return this.rebrandingCodeField;
            }
            set
            {
                this.rebrandingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.applicationNameField;
            }
            set
            {
                this.applicationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum PlatformEnum
    {
        
        /// <remarks/>
        Windows,
        
        /// <remarks/>
        macOS,
        
        /// <remarks/>
        Android,
        
        /// <remarks/>
        iOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseItemCollectionGetInfo
    {
        
        private SubscriptionInfo subscriptionField;
        
        private SubscriptionUsageInfo subscriptionUsageField;
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SubscriptionInfo Subscription
        {
            get
            {
                return this.subscriptionField;
            }
            set
            {
                this.subscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubscriptionUsageInfo SubscriptionUsage
        {
            get
            {
                return this.subscriptionUsageField;
            }
            set
            {
                this.subscriptionUsageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionInfo
    {
        
        private SubscriptionStatusEnum statusField;
        
        private System.DateTime statusChangeTimeField;
        
        private bool statusChangeTimeFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private string endTimeField;
        
        private string licenseCountField;
        
        private string productIdField;
        
        private string activationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubscriptionStatusEnum Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StatusChangeTime
        {
            get
            {
                return this.statusChangeTimeField;
            }
            set
            {
                this.statusChangeTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusChangeTimeSpecified
        {
            get
            {
                return this.statusChangeTimeFieldSpecified;
            }
            set
            {
                this.statusChangeTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified
        {
            get
            {
                return this.startTimeFieldSpecified;
            }
            set
            {
                this.startTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string LicenseCount
        {
            get
            {
                return this.licenseCountField;
            }
            set
            {
                this.licenseCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActivationCode
        {
            get
            {
                return this.activationCodeField;
            }
            set
            {
                this.activationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum SubscriptionStatusEnum
    {
        
        /// <remarks/>
        NotStarted,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        SoftCancelled,
        
        /// <remarks/>
        HardCancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionUsageInfo
    {
        
        private System.DateTime firstActivationTimeField;
        
        private bool firstActivationTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FirstActivationTime
        {
            get
            {
                return this.firstActivationTimeField;
            }
            set
            {
                this.firstActivationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstActivationTimeSpecified
        {
            get
            {
                return this.firstActivationTimeFieldSpecified;
            }
            set
            {
                this.firstActivationTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class BaseResponseItemType
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        Activate,
        
        /// <remarks/>
        GetDownloadLinks,
        
        /// <remarks/>
        GetInfo,
        
        /// <remarks/>
        HardCancel,
        
        /// <remarks/>
        Pause,
        
        /// <remarks/>
        Renew,
        
        /// <remarks/>
        Resume,
        
        /// <remarks/>
        SoftCancel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class TransactionErrorType
    {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestGetDownloadLinksItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string languageField;
        
        private string alphabetField;
        
        private string regionField;
        
        private string rebrandingCodeField;
        
        private PlatformEnum platformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alphabet
        {
            get
            {
                return this.alphabetField;
            }
            set
            {
                this.alphabetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RebrandingCode
        {
            get
            {
                return this.rebrandingCodeField;
            }
            set
            {
                this.rebrandingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PlatformEnum Platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestGetInfoItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private SubscriptionInfoType infoSectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubscriptionInfoType InfoSection
        {
            get
            {
                return this.infoSectionField;
            }
            set
            {
                this.infoSectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum SubscriptionInfoType
    {
        
        /// <remarks/>
        Subscription,
        
        /// <remarks/>
        SubscriptionUsage,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Subscription, SubscriptionUsage")]
        SubscriptionSubscriptionUsage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestPauseItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime pauseTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime PauseTime
        {
            get
            {
                return this.pauseTimeField;
            }
            set
            {
                this.pauseTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestResumeItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestHardCancelItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestSoftCancelItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestRenewItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private string endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestActivateItem
    {
        
        private string unitIdField;
        
        private string subscriberIdField;
        
        private System.DateTime startTimeField;
        
        private string endTimeField;
        
        private string licenseCountField;
        
        private string productIdField;
        
        private ActivationTypeEnum activationTypeField;
        
        public SubscriptionRequestActivateItem()
        {
            this.licenseCountField = "1";
            this.activationTypeField = ActivationTypeEnum.Standard;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string LicenseCount
        {
            get
            {
                return this.licenseCountField;
            }
            set
            {
                this.licenseCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ActivationTypeEnum.Standard)]
        public ActivationTypeEnum ActivationType
        {
            get
            {
                return this.activationTypeField;
            }
            set
            {
                this.activationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public enum ActivationTypeEnum
    {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Secondary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionRequestContainer
    {
        
        private System.DateTime timestampField;
        
        private string transactionIdField;
        
        private object[] subscriptionRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Activate", typeof(SubscriptionRequestActivateItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GetDownloadLinks", typeof(SubscriptionRequestGetDownloadLinksItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GetInfo", typeof(SubscriptionRequestGetInfoItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HardCancel", typeof(SubscriptionRequestHardCancelItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Pause", typeof(SubscriptionRequestPauseItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Renew", typeof(SubscriptionRequestRenewItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resume", typeof(SubscriptionRequestResumeItem), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SoftCancel", typeof(SubscriptionRequestSoftCancelItem), IsNullable=false)]
        public object[] SubscriptionRequest
        {
            get
            {
                return this.subscriptionRequestField;
            }
            set
            {
                this.subscriptionRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
    public partial class SubscriptionResponseContainer
    {
        
        private System.DateTime timestampField;
        
        private string transactionIdField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionError", typeof(SubscriptionResponseErrorCollection), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionResponse", typeof(SubscriptionResponseItemCollection), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("TransactionError", typeof(TransactionErrorType), Order=2)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionRequestRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/")]
        public UPI.AccessInfo AccessInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", Order=0)]
        public UPI.SubscriptionRequestContainer SubscriptionRequestContainer;
        
        public SubscriptionRequestRequest()
        {
        }
        
        public SubscriptionRequestRequest(UPI.AccessInfo AccessInfo, UPI.SubscriptionRequestContainer SubscriptionRequestContainer)
        {
            this.AccessInfo = AccessInfo;
            this.SubscriptionRequestContainer = SubscriptionRequestContainer;
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.kaspersky.com/services/subscription/2.0/", Order=0)]
        public UPI.SubscriptionResponseContainer SubscriptionResponseContainer;
        
        public SubscriptionRequestResponse()
        {
        }
        
        public SubscriptionRequestResponse(UPI.SubscriptionResponseContainer SubscriptionResponseContainer)
        {
            this.SubscriptionResponseContainer = SubscriptionResponseContainer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KasperskySubscriptionServicePortTypeChannel : UPI.KasperskySubscriptionServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KasperskySubscriptionServicePortTypeClient : System.ServiceModel.ClientBase<UPI.KasperskySubscriptionServicePortType>, UPI.KasperskySubscriptionServicePortType
    {
        
        public KasperskySubscriptionServicePortTypeClient()
        {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public KasperskySubscriptionServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public KasperskySubscriptionServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPI.SubscriptionRequestResponse UPI.KasperskySubscriptionServicePortType.SubscriptionRequest(UPI.SubscriptionRequestRequest request)
        {
            return base.Channel.SubscriptionRequest(request);
        }
        
        public UPI.SubscriptionResponseContainer SubscriptionRequest(UPI.AccessInfo AccessInfo, UPI.SubscriptionRequestContainer SubscriptionRequestContainer)
        {
            UPI.SubscriptionRequestRequest inValue = new UPI.SubscriptionRequestRequest();
            inValue.AccessInfo = AccessInfo;
            inValue.SubscriptionRequestContainer = SubscriptionRequestContainer;
            UPI.SubscriptionRequestResponse retVal = ((UPI.KasperskySubscriptionServicePortType)(this)).SubscriptionRequest(inValue);
            return retVal.SubscriptionResponseContainer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPI.SubscriptionRequestResponse> UPI.KasperskySubscriptionServicePortType.SubscriptionRequestAsync(UPI.SubscriptionRequestRequest request)
        {
            return base.Channel.SubscriptionRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPI.SubscriptionRequestResponse> SubscriptionRequestAsync(UPI.AccessInfo AccessInfo, UPI.SubscriptionRequestContainer SubscriptionRequestContainer)
        {
            UPI.SubscriptionRequestRequest inValue = new UPI.SubscriptionRequestRequest();
            inValue.AccessInfo = AccessInfo;
            inValue.SubscriptionRequestContainer = SubscriptionRequestContainer;
            return ((UPI.KasperskySubscriptionServicePortType)(this)).SubscriptionRequestAsync(inValue);
        }
    }
}
